name: SignTodos
main: Wertzui123\SignTodos\Main
version: 1.1.1
api: 3.0.0
author: Wertzui123
load: POSTWORLD
description: Ever forgot what you want to change in your buildings? Now you don't have to worry anymore!
website: https://github.com/Wertzui123
permissions:
  signtodos:
    default: op
    description: Permission for all SignTodos Features
    children:
      signtodos.cmd:
        default: op
        description: Permission for all SignTodos Commands
        children:
          signtodos.cmd.todos:
            default: op
            description: Permission for the /todos Command
      signtodos.destroy.others:
        default: op
        description: Permission for destroying others signtodos